[[redirects]]
  from = "/"
  to = "/v2"
  status = 301
  force = true

[[redirects]]
  from = "/v2/*"
  to = "/v2/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true 